### PR TITLE
Add Figma-Design folder

### PR DESCRIPTION
**Pull request by parinitapatil**
ADDED DESIGN FILE TO THE FORKED REPOSITORY
NAME: FIGMA-DESIGN
 by:@parinitapatil
 to:@YuriDevAT 

image

### CODE REVIEW

**Comment by parinitapatil** [comment]
If there are any changed do let me know

**Comment by YuriDevAT** [comment]
Wow, amazing job @parinitapatil . The dark mode looks great 🤩  
Could you please add the file with the link to the already existing folder `figma` inside the `public` folder?

**Comment by parinitapatil** [comment]
can you guide me how to do that , I am facing problem in that

**Comment by parinitapatil** [comment]
i have moved the **figma** folder to the **public** . if you want to access the link just click **ctrl + click**

image

**Comment by parinitapatil** [comment]
let me know if there's any problem

**Comment by YuriDevAT** [comment]
Very well done, @parinitapatil. Thank you for contributing to the project 🥳

**Pull request merged**
